// src/lib/components/Hobbies.svelte
<script lang="ts">
  import Panel from './Panel.svelte';
  import { t } from '$lib/i18n/translations';

  const tags = ['dev', 'homelab', 'movie', 'basket', 'running'] as const;
</script>

<Panel id="hobbies" header={$t('cv.hobbies.panelTitle')}>
  <div class="hobby">
    {#each tags as tag}
      <div class="hobby__tag">{$t(`cv.hobbies.content.${tag}`)}</div>
    {/each}
  </div>
</Panel>

// src/app/features/resume/components/hobbies/hobbies.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { TranslocoDirective } from '@jsverse/transloco';
import { PanelComponent } from '@shared/components/panel/panel.component';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PanelComponent, TranslocoDirective],
  selector: 'cv-hobbies',
  styleUrl: './hobbies.component.scss',
  templateUrl: './hobbies.component.html',
})
export class HobbiesComponent {
  protected readonly tags: string[] = [
    'cv.hobbies.content.dev',
    'cv.hobbies.content.homelab',
    'cv.hobbies.content.movie',
    'cv.hobbies.content.basket',
    'cv.hobbies.content.running',
  ];
}

<ng-container *transloco="let translate">
  <cv-panel id="hobbies" [header]="translate('cv.hobbies.panelTitle')">
    <div class="hobbies">
      <p-tag [rounded]="true">{{ translate('cv.hobbies.content.dev') }}</p-tag>
      <p-tag [rounded]="true">{{ translate('cv.hobbies.content.homelab') }}</p-tag>
      <p-tag [rounded]="true">{{ translate('cv.hobbies.content.movie') }}</p-tag>
      <p-tag [rounded]="true">{{ translate('cv.hobbies.content.basket') }}</p-tag>
      <p-tag [rounded]="true">{{ translate('cv.hobbies.content.running') }}</p-tag>
    </div>
  </cv-panel>
</ng-container>
