// src/lib/components/SlideButton.svelte
<script lang="ts">
  let { label, missionIndex }: { label: string; missionIndex: number } = $props();
</script>

<button class="learn-more" type="button" data-mission={missionIndex} aria-label={label}>
  <span class="circle" aria-hidden="true">
    <span class="icon arrow"></span>
  </span>
  <span class="button-text">{label}</span>
</button>

// src/app/shared/components/slide-button/slide-button.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'portfolio-slide-button',
  templateUrl: './slide-button.component.html',
  styleUrls: ['./slide-button.component.scss'],
})
export class SlideButtonComponent {}

<ng-container *transloco="let translate">
  <button class="learn-more">
    <span class="circle" aria-hidden="true">
      <span class="icon arrow"></span>
    </span>
    <span class="button-text">{{ translate('cv.shared.slideButton') }}</span>
  </button>
</ng-container>
