// src/app/features/resume/components/skills/skills.component.ts
import { AfterViewInit, Component, Input } from '@angular/core';
import { Skill } from '@core/models/skill.model';

@Component({
  selector: 'portfolio-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss'],
})
export class SkillsComponent implements AfterViewInit {
  @Input() skills: Skill[] = [];
  @Input() clones: Skill[] = [];

  /**
   * @inheritDoc
   */
  ngAfterViewInit(): void {
    this._animateSkillsOnView();
  }

  /**
   * Animate the skills bar when visible on screen
   */
  private _animateSkillsOnView(): void {
    const rateIntersectionObserver = new IntersectionObserver(
      (entries: IntersectionObserverEntry[]) => {
        entries.forEach((entry: IntersectionObserverEntry) => {
          if (entry.isIntersecting && this.clones.length > 0) {
            this.skills.forEach(
              (tool: Skill) => (tool.rate = this.clones?.find((clone: Skill) => clone.name === tool.name)?.rate!)
            );
          }
        });
      },
      {
        threshold: 0,
      }
    );
    const rateElement = document.querySelector('p-panel[header="Langages et outils"] .p-component');
    if (rateElement) rateIntersectionObserver.observe(rateElement);
  }
}

<ng-container *transloco="let translate">
  <p-panel id="skills" [header]="translate('cv.skills.panelTitle')">
    <div class="skills">
      @if (!!_skills && !!_clones) {
        @for (skill of _skills; track skill.name) {
          <div class="skills__languages">
            <span>{{ skill.name }}</span>
<!--            <p-progressBar [value]="skill.rate" [showValue]="false"></p-progressBar>-->
            <cv-progress-bar [value]="skill.rate"></cv-progress-bar>
          </div>
        }
      }
    </div>
  </p-panel>
</ng-container>

// src/lib/components/Skills.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Panel from './Panel.svelte';
  import ProgressBar from './ProgressBar.svelte';
  import { t } from '$lib/i18n/translations';

  let { skills }: { skills: { name: string; rate: number }[] } = $props();

  onMount(() => {
    const panel = document.getElementById('skills');
    const bars = document.querySelectorAll<HTMLElement>('#skills .progress-bar');
    if (!panel || bars.length === 0) return;

    const animate = (): void => {
      bars.forEach((bar) => {
        const fill = bar.querySelector<HTMLElement>('.progress-bar__value');
        if (fill) fill.style.width = `${bar.dataset.target ?? '0'}%`;
      });
    };

    const reset = (): void => {
      bars.forEach((bar) => {
        const fill = bar.querySelector<HTMLElement>('.progress-bar__value');
        if (fill) fill.style.width = '0%';
      });
    };

    const rect = panel.getBoundingClientRect();
    if (rect.top < window.innerHeight && rect.bottom > 0) animate();

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => { entry.isIntersecting ? animate() : reset(); });
    }, { threshold: 0 });

    observer.observe(panel);
    return () => observer.disconnect();
  });
</script>

<Panel id="skills" header={$t('cv.skills.panelTitle')}>
  <div class="skills">
    {#each skills as skill}
      <div class="skills__languages">
        <span>{skill.name}</span>
        <ProgressBar value={skill.rate} name={skill.name} />
      </div>
    {/each}
  </div>
</Panel>
